#!/usr/bin/env python3
"""
Script to update README.md with a random daily tip/advice.
Updates content between <!-- START_DAILY_TIP --> and <!-- END_DAILY_TIP --> markers.
"""

import random
import re
from pathlib import Path


# List of tips related to programming, IT, and personal productivity
TIPS = [
    "The code you don't have to write is the best code. Always look for ready-made solutions before writing your own.",
    "Commit often with clear messages. Your future self will thank you.",
    "Refactoring is not a waste of time, it's an investment in your project's future.",
    "Learn one new tool or technology every month. Continuous learning is the key to growth.",
    "Document code for people, not for computers. Clarity is more important than brevity.",
    "Test your code. A bug found during development costs 10 times less than in production.",
    "Take breaks. The best solutions often come when you're not staring at the monitor.",
    "Code review is not criticism, but an opportunity to learn something new from colleagues.",
    "Automate routine tasks. If you do something more than twice — write a script.",
    "Security is not an option, it's a necessity. Never commit secrets and API keys to a repository.",
    "Write code as if the person maintaining it is a violent psychopath who knows where you live.",
    "The best time to fix a bug is before it reaches production.",
    "Your code should be self-explanatory, but comments explain the why, not the what.",
    "Learn keyboard shortcuts. They save more time than you think.",
    "Don't optimize prematurely. Make it work, then make it fast.",
    "Version control is not optional. Every project deserves Git.",
    "Read other people's code. It's the fastest way to improve.",
    "Pair programming isn't twice as slow; it's twice as smart.",
    "The delete key is your friend. Don't be afraid to remove code.",
    "A good developer writes code. A great developer deletes code.",
    "Learn the command line. It's powerful and universal.",
    "Test edge cases. Users will find ways to break your app you never imagined.",
    "Keep your dependencies up to date, but not bleeding edge.",
    "Rubber duck debugging works. Explaining your problem often reveals the solution.",
    "Write tests first, code second. TDD saves time in the long run.",
    "Don't repeat yourself (DRY). Duplication is the root of maintenance evil.",
    "KISS: Keep It Simple, Stupid. Complexity is the enemy of reliability.",
    "YAGNI: You Aren't Gonna Need It. Don't build features you don't need yet.",
    "Naming is hard. Spend time on good variable and function names.",
    "Code for humans first, machines second.",
    "Learn regex. It's powerful for text processing.",
    "Master your IDE. Tools make you productive.",
    "Read error messages carefully. They usually tell you what's wrong.",
    "Stack Overflow is a resource, not a solution. Understand before copying.",
    "Learn data structures and algorithms. They're the foundation of good code.",
    "Design patterns are tools, not rules. Use them wisely.",
    "The best code is no code at all.",
    "Performance matters, but correctness matters more.",
    "Security is everyone's responsibility, not just the security team's.",
    "Learn to debug efficiently. Print statements are just the beginning.",
    "Version everything: code, configurations, documentation.",
    "Continuous integration catches bugs early.",
    "Deploy often, deploy small. Small changes are easier to debug.",
    "Monitor your applications. You can't fix what you don't know is broken.",
    "Log intelligently. Too much logging is noise, too little is blindness.",
    "Backup everything. Disasters happen.",
    "Learn SQL. Data is at the heart of most applications.",
    "REST APIs should be intuitive and consistent.",
    "Write API documentation. Your users will thank you.",
    "Error handling is not optional. Plan for failure.",
    "Don't trust user input. Validate and sanitize everything.",
    "Use meaningful commit messages. 'Fixed stuff' helps no one.",
    "Branch strategically. Master should always be deployable.",
    "Code reviews improve code quality and share knowledge.",
    "Automate your deployment. Manual deployments lead to errors.",
    "Learn Docker. Containers solve many environment issues.",
    "Understand the CAP theorem. Distributed systems have tradeoffs.",
    "Caching is powerful but can cause subtle bugs.",
    "Know the difference between authentication and authorization.",
    "Use environment variables for configuration, not hardcoded values.",
    "Learn about time zones. They're more complex than you think.",
    "Floating point arithmetic is not exact. Be careful with money calculations.",
    "Off-by-one errors are more common than you think.",
    "Learn about character encodings. UTF-8 is your friend.",
    "Regular expressions are powerful but can be cryptic. Comment complex ones.",
    "Understand HTTP status codes. 200, 404, 500 are just the beginning.",
    "Learn about CORS. It will save you hours of debugging.",
    "Use linters. They catch errors before runtime.",
    "Code formatters remove style debates. Use them.",
    "Static type checking prevents many runtime errors.",
    "Learn functional programming concepts. They improve code quality.",
    "Immutability prevents many bugs.",
    "Pure functions are easier to test and reason about.",
    "Side effects should be isolated and explicit.",
    "Learn about recursion, but use iteration when simpler.",
    "Understand Big O notation. Algorithmic complexity matters at scale.",
    "Hash tables are fast for lookups. Learn when to use them.",
    "Binary search is O(log n). Use it for sorted data.",
    "Trees are fundamental. Learn about binary trees, BSTs, and tries.",
    "Graphs model relationships. BFS and DFS are essential algorithms.",
    "Dynamic programming solves complex problems efficiently.",
    "Greedy algorithms are simple but don't always give optimal solutions.",
    "Learn about sorting algorithms. Each has its use case.",
    "Understand space-time tradeoffs. More memory can mean faster code.",
    "Premature optimization is the root of all evil, but algorithmic choice matters.",
    "Learn about design patterns: Singleton, Factory, Observer, Strategy.",
    "MVC separates concerns. Use it for maintainable applications.",
    "Dependency injection makes code testable and flexible.",
    "Learn about SOLID principles: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.",
    "Composition over inheritance. Favor has-a over is-a relationships.",
    "Interfaces define contracts. Implementations can vary.",
    "Abstraction hides complexity. Use it to simplify your code.",
    "Encapsulation protects data. Make fields private, expose through methods.",
    "Polymorphism allows flexibility. Code to interfaces, not implementations.",
    "Learn about threads and concurrency. Parallel execution is powerful but tricky.",
    "Race conditions are subtle. Synchronize access to shared resources.",
    "Deadlocks happen. Understand how to prevent them.",
    "Async/await makes asynchronous code readable.",
    "Promises simplify callback hell.",
    "Learn about event loops. They power JavaScript and many frameworks.",
    "Microservices have benefits but add complexity. Choose wisely.",
    "Monoliths are not evil. They're simpler for many applications.",
    "Service-oriented architecture separates concerns across network boundaries.",
    "APIs should be versioned. Breaking changes need new versions.",
    "GraphQL gives clients flexibility but adds complexity.",
    "WebSockets enable real-time communication.",
    "Learn about message queues. They decouple services.",
    "Eventual consistency is a tradeoff in distributed systems.",
    "Learn about databases: SQL for structured data, NoSQL for flexibility.",
    "Normalize your database schema to reduce redundancy.",
    "Denormalization can improve read performance.",
    "Indexes speed up queries but slow down writes.",
    "Learn about database transactions and ACID properties.",
    "N+1 queries are a common performance problem. Use joins or eager loading.",
    "Learn about ORMs. They simplify database access but can hide performance issues.",
    "Database migrations should be versioned and automated.",
    "Learn about connection pooling. Database connections are expensive.",
    "Understand database locking. It prevents race conditions but can cause deadlocks.",
    "Learn about sharding. It scales databases horizontally.",
    "Replication provides redundancy and read scalability.",
    "Learn about caching strategies: read-through, write-through, write-behind.",
    "Redis is great for caching and simple data structures.",
    "Learn about CDNs. They speed up content delivery globally.",
    "Load balancers distribute traffic across servers.",
    "Learn about horizontal and vertical scaling.",
    "Auto-scaling adapts to load automatically.",
    "Learn about cloud services: AWS, Azure, Google Cloud.",
    "Infrastructure as Code makes deployments reproducible.",
    "Learn about CI/CD pipelines. Automate testing and deployment.",
    "Feature flags allow deploying code without activating features.",
    "Canary deployments reduce risk by rolling out gradually.",
    "Blue-green deployments enable zero-downtime updates.",
    "Learn about monitoring and alerting. Know when things break.",
    "Logs should be structured and searchable.",
    "Distributed tracing helps debug microservices.",
    "Learn about APM tools. They show application performance bottlenecks.",
    "Error tracking services catch exceptions in production.",
    "Learn about load testing. Know your system's limits.",
    "Security should be built in, not bolted on.",
    "Learn about OWASP Top 10. These are the most critical security risks.",
    "SQL injection is preventable. Use parameterized queries.",
    "XSS attacks are common. Sanitize user input and escape output.",
    "CSRF attacks are preventable. Use tokens.",
    "Learn about encryption: symmetric vs asymmetric.",
    "HTTPS is not optional. Encrypt data in transit.",
    "Salt and hash passwords. Never store them in plain text.",
    "Use bcrypt or Argon2 for password hashing.",
    "Multi-factor authentication greatly improves security.",
    "Least privilege principle: grant minimum necessary permissions.",
    "Keep secrets out of code. Use secret management services.",
    "Learn about OAuth 2.0 for authorization.",
    "JWT tokens are stateless but can't be revoked easily.",
    "Learn about rate limiting. Prevent abuse of your APIs.",
    "Input validation prevents many security issues.",
    "Learn about dependency vulnerabilities. Keep libraries updated.",
    "Security audits should be regular, not one-time.",
    "Learn about penetration testing. Find vulnerabilities before attackers do.",
    "Bug bounty programs leverage external security researchers.",
    "Learn about compliance: GDPR, HIPAA, PCI-DSS.",
    "Privacy by design builds privacy into systems from the start.",
    "Learn about responsive design. Mobile users are the majority.",
    "Accessibility is not optional. Build for everyone.",
    "Learn about semantic HTML. It improves SEO and accessibility.",
    "CSS Grid and Flexbox make layout easier.",
    "Learn about progressive enhancement and graceful degradation.",
    "Page speed matters. Users abandon slow sites.",
    "Images should be optimized. Large files slow page loads.",
    "Learn about lazy loading. Load content as needed.",
    "Service workers enable offline functionality.",
    "Progressive Web Apps blur the line between web and native.",
    "Learn about browser developer tools. They're essential for debugging.",
    "Cross-browser testing ensures consistent experience.",
    "Learn about web performance metrics: FCP, LCP, TTI, CLS.",
    "A/B testing shows what users prefer.",
    "Analytics reveal how users actually use your app.",
    "User research prevents building features nobody wants.",
    "Learn about UX principles. Good design is invisible.",
    "Consistency improves usability. Reuse patterns.",
    "Feedback helps users understand what's happening.",
    "Error messages should be helpful, not cryptic.",
    "Learn about color theory and contrast for readability.",
    "Typography affects readability. Choose fonts carefully.",
    "White space improves visual clarity.",
    "Mobile-first design prioritizes the constrained environment.",
    "Learn about design systems. They ensure consistency.",
    "Wireframes and mockups clarify requirements before coding.",
    "Prototypes validate ideas cheaply.",
    "Iterate based on feedback. First versions are rarely perfect.",
    "Learn about Agile methodology. Flexibility and iteration are valuable.",
    "Scrum provides structure for Agile teams.",
    "Kanban visualizes work and limits work in progress.",
    "Stand-ups keep teams aligned.",
    "Retrospectives drive continuous improvement.",
    "User stories focus on value to users.",
    "Acceptance criteria define when a story is done.",
    "Technical debt accumulates. Schedule time to pay it down.",
    "Learn about estimation techniques: story points, planning poker.",
    "Velocity helps predict future capacity.",
    "Sprint planning sets realistic goals.",
    "Sprint reviews demonstrate progress to stakeholders.",
    "Continuous improvement is a mindset, not a phase.",
    "Learn about DevOps culture. Development and operations should collaborate.",
    "Blameless post-mortems focus on learning, not punishment.",
    "Documentation is code's best friend. Keep it updated.",
    "README files should explain what, why, and how.",
    "API documentation should include examples.",
    "Architecture diagrams communicate system design.",
    "Decision records document why choices were made.",
    "Learn about open source. Contributing helps you and the community.",
    "Open source licenses matter. Choose carefully.",
    "Contributing guidelines help new contributors.",
    "Code of conduct sets community expectations.",
    "Learn about semantic versioning: major.minor.patch.",
    "Changelogs help users understand what changed.",
    "Learn about networking: TCP/IP, DNS, HTTP, WebSockets.",
    "Latency and bandwidth are different. Both matter.",
    "Learn about CDNs. They reduce latency by serving content closer to users.",
    "DNS is the internet's phone book. Understand how it works.",
    "Learn about SSL/TLS. Encryption protects data in transit.",
    "Load balancers distribute traffic and provide redundancy.",
    "Learn about proxies and reverse proxies.",
    "VPNs create secure tunnels over untrusted networks.",
    "Firewalls control network traffic based on rules.",
    "Learn about IPv6. IPv4 addresses are running out.",
    "Learn about operating systems: processes, threads, memory management.",
    "Linux is everywhere. Learn basic commands.",
    "Shell scripting automates tasks.",
    "Learn about package managers: apt, yum, brew, npm, pip.",
    "Cronjobs schedule recurring tasks.",
    "Environment variables configure applications.",
    "Learn about system calls. They're how programs interact with the OS.",
    "Virtual machines isolate environments.",
    "Containers are lighter than VMs.",
    "Kubernetes orchestrates containers at scale.",
    "Learn about serverless computing. Pay only for what you use.",
    "Edge computing brings computation closer to data sources.",
    "Learn about IoT. Connected devices are everywhere.",
    "Machine learning is powerful but requires good data.",
    "Learn about AI ethics. Technology should be used responsibly.",
    "Data science extracts insights from data.",
    "Learn about big data technologies: Hadoop, Spark.",
    "Data visualization makes insights accessible.",
    "Learn about statistics. It's the foundation of data analysis.",
    "Correlation does not imply causation.",
    "Learn about probability. It quantifies uncertainty.",
    "A/B testing requires statistical significance.",
    "Learn about bias in data and algorithms.",
    "Privacy is important. Handle user data responsibly.",
    "Learn about blockchain. It's more than just cryptocurrency.",
    "Smart contracts automate agreements.",
    "Learn about quantum computing. It's the future of computation.",
    "Moore's Law is slowing. Efficiency matters more than ever.",
    "Learn about green computing. Technology has environmental impact.",
    "Remote work requires good communication tools.",
    "Asynchronous communication respects time zones.",
    "Video calls are useful but tiring. Balance them with async work.",
    "Written communication should be clear and concise.",
    "Learn to write good emails. They're still widely used.",
    "Slack and similar tools enable quick communication.",
    "Documentation reduces the need for synchronous communication.",
    "Time management is crucial. Prioritize important over urgent.",
    "Learn about the Eisenhower Matrix for prioritization.",
    "Pomodoro technique: work in focused 25-minute blocks.",
    "Deep work requires uninterrupted time. Block your calendar.",
    "Multitasking is a myth. Focus on one thing at a time.",
    "Learn to say no. You can't do everything.",
    "Delegate when possible. It scales your impact.",
    "Automate repetitive tasks. Your time is valuable.",
    "Learn about inbox zero. Email shouldn't control your day.",
    "Take regular breaks. Your brain needs rest.",
    "Exercise improves focus and health.",
    "Sleep is not optional. It's when your brain consolidates learning.",
    "Meditation reduces stress and improves focus.",
    "Learn about work-life balance. Burnout helps no one.",
    "Hobbies outside tech keep you creative.",
    "Social connections matter. Don't isolate yourself.",
    "Mentorship accelerates growth. Find mentors and mentor others.",
    "Networking builds relationships. Attend meetups and conferences.",
    "Public speaking improves with practice.",
    "Writing clarifies thinking. Blog about what you learn.",
    "Teaching others deepens your understanding.",
    "Learn continuously. Technology evolves rapidly.",
    "Read books. They provide depth that articles lack.",
    "Follow thought leaders in your field.",
    "Listen to podcasts during commutes or exercise.",
    "Take online courses. There are great resources for every topic.",
    "Certifications can validate skills but aren't everything.",
    "Side projects let you experiment without constraints.",
    "Open source contributions build your portfolio.",
    "Build things. Learning by doing is most effective.",
    "Ship often. Done is better than perfect.",
    "Get feedback early. It's cheaper to change direction early.",
    "Fail fast. Learn from mistakes and move on.",
    "Celebrate small wins. Progress is motivating.",
    "Reflect regularly. What's working? What isn't?",
    "Set goals. They provide direction.",
    "Break big goals into small steps.",
    "Track your progress. It reveals patterns.",
    "Learn about growth mindset. Abilities can be developed.",
    "Imposter syndrome is common. You're not alone.",
    "Compare yourself to past you, not to others.",
    "Perfectionism is the enemy of done.",
    "Good enough is often actually good enough.",
    "Learn from criticism. It's feedback, not attack.",
    "Give constructive feedback. Be specific and kind.",
    "Empathy makes you a better teammate.",
    "Listen actively. Understand before responding.",
    "Ask questions. There are no stupid questions.",
    "Admit when you don't know something. It's a strength, not weakness.",
    "Learn about different learning styles. Find what works for you.",
    "Spaced repetition aids long-term retention.",
    "Active recall is more effective than passive reading.",
    "Learn by teaching. Explaining solidifies understanding.",
    "Practice deliberately. Focus on weaknesses.",
    "Seek challenging problems. Comfort zones don't grow skills.",
    "Learn about cognitive biases. They affect decision-making.",
    "Confirmation bias seeks evidence that supports existing beliefs.",
    "Sunk cost fallacy keeps you invested in bad decisions.",
    "Analysis paralysis prevents action. Sometimes you must decide with incomplete information.",
    "Learn about decision-making frameworks.",
    "Pros and cons lists clarify tradeoffs.",
    "Cost-benefit analysis quantifies decisions.",
    "Risk assessment prepares for potential problems.",
    "Learn about leadership. It's influence, not just authority.",
    "Trust is earned through consistency.",
    "Transparency builds trust.",
    "Accountability means owning your mistakes.",
    "Recognition motivates. Celebrate others' achievements.",
    "Delegation empowers team members.",
    "Learn about conflict resolution. Disagreements are opportunities.",
    "Focus on interests, not positions, in negotiations.",
    "Win-win solutions are possible and preferable.",
    "Learn about emotional intelligence. It matters as much as IQ.",
    "Self-awareness is the foundation of emotional intelligence.",
    "Self-regulation manages emotions constructively.",
    "Motivation drives persistence.",
    "Empathy understands others' perspectives.",
    "Social skills build relationships.",
    "Learn about diversity and inclusion. Different perspectives improve solutions.",
    "Unconscious bias affects everyone. Awareness is the first step.",
    "Inclusive language makes everyone feel welcome.",
    "Learn about accessibility. Everyone deserves equal access.",
    "Privilege is invisible to those who have it. Listen to those without it.",
    "Allyship is active support, not passive agreement.",
    "Learn about sustainability. Think long-term.",
    "Technical solutions should consider environmental impact.",
    "Efficiency reduces resource usage.",
    "Learn about circular economy. Waste can be resource.",
    "Renewable energy powers sustainable computing.",
    "Learn about ethics in technology. Consider implications of your work.",
    "Privacy is a human right. Respect user data.",
    "Surveillance technology has social implications.",
    "AI can perpetuate bias if not carefully designed.",
    "Autonomous systems raise moral questions.",
    "Learn about digital divide. Not everyone has equal access to technology.",
    "Technology should empower, not control.",
    "Learn about digital wellness. Technology should serve you, not vice versa.",
    "Notifications can wait. Control them, don't let them control you.",
    "Screen time affects sleep. Blue light disrupts circadian rhythms.",
    "Digital detoxes refresh perspective.",
    "Learn about information overload. Curation beats consumption.",
    "Focus on depth over breadth. Master before moving on.",
    "Learn about curiosity. It drives innovation.",
    "Question assumptions. They may be outdated.",
    "Experiment often. Hypothesis-driven exploration accelerates learning.",
    "Learn from failures. They're data points, not verdicts.",
    "Pivot when necessary. Persistence in wrong direction is waste.",
    "Learn about innovation. New combinations create value.",
    "Constraints spark creativity.",
    "Learn about design thinking. Empathy, ideation, experimentation.",
    "Brainstorming generates options. Defer judgment initially.",
    "Prototypes test ideas cheaply.",
    "Learn about lean startup. Build, measure, learn.",
    "MVP tests assumptions with minimum effort.",
    "Product-market fit is essential. Build what people want.",
    "Learn about business models. How does it create and capture value?",
    "Unit economics determine long-term viability.",
    "Learn about fundraising if building a startup.",
    "Learn about bootstrapping. Profitability gives independence.",
    "Customer development validates assumptions.",
    "Learn about marketing. Great products need visibility.",
    "Content marketing attracts through value.",
    "SEO makes your content discoverable.",
    "Social media builds community.",
    "Email marketing has high ROI.",
    "Learn about sales. It's not manipulation, it's problem-solving.",
    "Understand customer pain points. Solutions sell.",
    "Learn about customer success. Retention beats acquisition.",
    "Churn rate indicates product-market fit.",
    "Net Promoter Score measures customer satisfaction.",
    "Learn about support. Happy customers become advocates.",
    "Learn about careers in tech. Many paths exist.",
    "Software engineering builds products.",
    "Data science extracts insights.",
    "DevOps bridges development and operations.",
    "Security protects systems.",
    "Product management defines what to build.",
    "Design creates user experience.",
    "QA ensures quality.",
    "Technical writing explains complexity.",
    "Developer relations builds community.",
    "Learn about interviews. Preparation matters.",
    "Practice coding problems. Leetcode, HackerRank, etc.",
    "System design questions test architecture skills.",
    "Behavioral questions assess cultural fit.",
    "Ask good questions. Interviews are two-way.",
    "Learn about negotiation. Compensation is negotiable.",
    "Total compensation includes salary, equity, benefits.",
    "Equity can be valuable but is risky.",
    "Learn about job satisfaction. Money isn't everything.",
    "Growth opportunities matter. Skills compound.",
    "Work environment affects happiness and productivity.",
    "Team quality predicts job satisfaction.",
    "Learn about company culture. It's how things actually get done.",
    "Mission and values guide decisions.",
    "Learn about career growth. Lateral moves can be strategic.",
    "Specialists go deep. Generalists go broad. Both have value.",
    "T-shaped skills combine depth and breadth.",
    "Learn about personal brand. Reputation precedes you.",
    "Online presence matters. Google yourself.",
    "Portfolio demonstrates skills better than resume.",
    "GitHub profile shows your code.",
    "LinkedIn builds professional network.",
    "Twitter connects you with communities.",
    "Learn about luck. You can increase your surface area.",
    "Serendipity comes from trying many things.",
    "Network effects compound. Connections create opportunities.",
    "Learn about patience. Mastery takes time.",
    "Consistency beats intensity. Daily progress accumulates.",
    "Long-term thinking pays off. Compound effects are powerful.",
    "Every expert was once a beginner. Start where you are.",
    "The journey is the destination. Enjoy the process.",
    "Stay curious. Learning never ends.",
]

# Markers to identify the section in README.md
START_MARKER = "<!-- START_DAILY_TIP -->"
END_MARKER = "<!-- END_DAILY_TIP -->"


def get_random_tip():
    """Select and format a random tip."""
    tip = random.choice(TIPS)
    return f"\n> 💡 **Tip of the Day:** {tip}\n"


def update_readme(readme_path):
    """
    Update README.md file with a new random tip.
    
    Args:
        readme_path: Path to the README.md file
        
    Returns:
        bool: True if file was updated, False otherwise
    """
    try:
        # Read the current README content
        with open(readme_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if markers exist
        if START_MARKER not in content or END_MARKER not in content:
            print(f"Error: Markers not found in {readme_path}")
            print(f"Please add {START_MARKER} and {END_MARKER} to your README.md")
            return False
        
        # Get a random tip
        new_tip = get_random_tip()
        
        # Replace content between markers
        pattern = f"{re.escape(START_MARKER)}.*?{re.escape(END_MARKER)}"
        replacement = f"{START_MARKER}{new_tip}{END_MARKER}"
        
        updated_content = re.sub(
            pattern,
            replacement,
            content,
            flags=re.DOTALL
        )
        
        # Check if content actually changed
        if updated_content == content:
            print("Content is already up to date")
            return False
        
        # Write updated content back to file
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)
        
        print(f"✅ Successfully updated {readme_path}")
        print(f"New tip: {new_tip.strip()}")
        return True
        
    except FileNotFoundError:
        print(f"Error: {readme_path} not found")
        return False
    except Exception as e:
        print(f"Error updating README: {e}")
        return False


def main():
    """Main function to run the update."""
    readme_path = Path(__file__).parent / "README.md"
    
    print("🔄 Starting README update...")
    success = update_readme(readme_path)
    
    if success:
        print("✨ Update completed successfully!")
    else:
        print("⚠️  Update failed or no changes needed")


if __name__ == "__main__":
    main()
